# Generated by Django 6.0.2 on 2026-02-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_remove_seat_is_booked_remove_seat_showtime_showseat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='number',
            new_name='column',
        ),
    ]
