# Generated by Django 6.0.2 on 2026-02-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_ticket_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.AddField(
            model_name='showtime',
            name='seat_column',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='showtime',
            name='seat_row',
            field=models.IntegerField(null=True),
        ),
    ]
