# Generated by Django 6.0.2 on 2026-02-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_delete_seat_showtime_seat_column_showtime_seat_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='number',
        ),
    ]
