# Generated by Django 6.0.2 on 2026-02-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_remove_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(1, 'reserved'), (2, 'booked')], default=1),
        ),
    ]
