# Generated by Django 6.0.2 on 2026-02-22 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showseat',
            name='location',
        ),
    ]
