# Generated by Django 6.0.2 on 2026-02-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0010_remove_showseat_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reserved_seats',
            field=models.JSONField(default=dict),
        ),
    ]
