# Generated by Django 6.0.2 on 2026-02-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_ticket_reserved_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='reserved_seats',
        ),
    ]
