# Generated by Django 6.0.2 on 2026-02-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_remove_ticket_reserved_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.JSONField(default=dict),
        ),
    ]
