# Generated by Django 6.0.2 on 2026-02-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0013_ticket_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
