# Generated by Django 6.0.2 on 2026-02-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_remove_cart_session_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
