# Generated by Django 6.0.2 on 2026-02-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0018_order_created_at_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(1, 'reserved'), (2, 'booked'), (3, 'completed'), (4, 'canceled')], default=1),
        ),
    ]
