# Generated by Django 6.0.2 on 2026-03-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0020_ticket_created_at_ticket_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtime',
            name='status',
            field=models.IntegerField(choices=[(1, 'open'), (2, 'running'), (3, 'finished'), (4, 'cancelled')], default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(1, 'reserved'), (2, 'booked'), (3, 'completed'), (4, 'cancelled')], default=1),
        ),
    ]
