# Generated by Django 6.0.2 on 2026-03-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0021_showtime_status_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='run_time',
            field=models.TimeField(),
        ),
    ]
