# Generated by Django 6.0.2 on 2026-03-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0023_alter_movie_run_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='run_time',
            field=models.TimeField(),
        ),
    ]
