# Generated by Django 6.0.3 on 2026-03-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.JSONField(default=dict)),
                ('amount', models.FloatField()),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'completed')], default=1)),
                ('items', models.JSONField(default=dict)),
                ('user', models.CharField(max_length=50)),
                ('payment_method', models.IntegerField(choices=[(1, 'stripe')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
